name: flutter_webapplication
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  http: ^1.3.0  
  flutter_form_builder: ^9.7.0  # This package helps in creation of data collection forms in Flutter
  form_builder_validators: ^11.1.1  # Form Builder Validators set of validators
  animate_do: ^3.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true